# Generated by Django 5.2.10 on 2026-01-09 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='Mi Gimnasio', max_length=200, verbose_name='Nombre del gimnasio')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('days_for_abandonment_alert', models.PositiveIntegerField(default=15, verbose_name='Días para alerta de abandono')),
                ('days_for_renewal_reminder', models.PositiveIntegerField(default=7, verbose_name='Días antes para recordatorio de renovación')),
                ('logo_url', models.CharField(blank=True, max_length=255, verbose_name='URL del logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color primario')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Gimnasio',
                'verbose_name_plural': 'Configuraciones del Gimnasio',
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de métrica')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('body_composition', 'Composición corporal'), ('strength', 'Fuerza'), ('endurance', 'Resistencia'), ('flexibility', 'Flexibilidad'), ('cardio', 'Cardiovascular'), ('nutrition', 'Nutrición'), ('wellness', 'Bienestar'), ('custom', 'Personalizado')], default='custom', max_length=30, verbose_name='Categoría')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras'), ('cm', 'Centímetros'), ('in', 'Pulgadas'), ('min', 'Minutos'), ('sec', 'Segundos'), ('rep', 'Repeticiones'), ('percent', 'Porcentaje'), ('bpm', 'Latidos por minuto'), ('cal', 'Calorías'), ('km', 'Kilómetros'), ('count', 'Cantidad'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Unidad de medida')),
                ('custom_unit', models.CharField(blank=True, max_length=50, verbose_name='Unidad personalizada')),
                ('is_higher_better', models.BooleanField(default=True, help_text='Si es True, valores más altos indican mejora. Si es False, valores más bajos son mejores (ej: % grasa)', verbose_name='Mayor es mejor')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor máximo')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color para gráficas')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Métrica',
                'verbose_name_plural': 'Tipos de Métricas',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('payment', 'Pago'), ('membership', 'Membresía'), ('other', 'Otro')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo afectado')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID del objeto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Valores anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Valores nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('recorded_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('recorded_time', models.TimeField(blank=True, null=True, verbose_name='Hora de registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('source', models.CharField(blank=True, help_text='Ej: manual, app, báscula inteligente', max_length=50, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_metrics', to='members.member', verbose_name='Miembro')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='analytics.metrictype', verbose_name='Tipo de métrica')),
            ],
            options={
                'verbose_name': 'Métrica del Atleta',
                'verbose_name_plural': 'Métricas del Atleta',
                'ordering': ['-recorded_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor inicial')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor objetivo')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor actual')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('target_date', models.DateField(verbose_name='Fecha objetivo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('achieved', 'Lograda'), ('failed', 'No lograda'), ('abandoned', 'Abandonada')], default='active', max_length=20, verbose_name='Estado')),
                ('achieved_date', models.DateField(blank=True, null=True, verbose_name='Fecha de logro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='members.member', verbose_name='Miembro')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='analytics.metrictype', verbose_name='Tipo de métrica')),
            ],
            options={
                'verbose_name': 'Meta de Rendimiento',
                'verbose_name_plural': 'Metas de Rendimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('training_type', models.CharField(help_text='Ej: Cardio, Fuerza, HIIT, Yoga', max_length=100, verbose_name='Tipo de entrenamiento')),
                ('intensity', models.CharField(choices=[('low', 'Baja'), ('moderate', 'Moderada'), ('high', 'Alta'), ('max', 'Máxima')], default='moderate', max_length=20, verbose_name='Intensidad')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías quemadas')),
                ('exercises_data', models.JSONField(blank=True, default=list, help_text='JSON con ejercicios realizados, series, repeticiones, peso', verbose_name='Datos de ejercicios')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('mood_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estado de ánimo antes (1-5)')),
                ('mood_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estado de ánimo después (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='classes.gymclass', verbose_name='Clase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='members.member', verbose_name='Miembro')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='classes.routine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Log de Entrenamiento',
                'verbose_name_plural': 'Logs de Entrenamiento',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de período')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('metrics_data', models.JSONField(default=dict, help_text='JSON con promedios, máximos, mínimos de cada métrica', verbose_name='Datos de métricas')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen del período')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Snapshot de Métricas',
                'verbose_name_plural': 'Snapshots de Métricas',
                'ordering': ['-period_end'],
                'unique_together': {('member', 'period_type', 'period_start')},
            },
        ),
    ]
