# Generated by Django 5.2.8 on 2026-02-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('experience_summary', models.TextField()),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('REVIEWED', 'Revisado'), ('CONTACTED', 'Contactado'), ('REJECTED', 'Rechazado'), ('HIRED', 'Contratado')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Empleo',
                'verbose_name_plural': 'Solicitudes de Empleo',
                'ordering': ['-created_at'],
            },
        ),
    ]
