# Generated by Django 5.2.10 on 2026-01-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duration_days', models.PositiveIntegerField(help_text='30 = mensual, 90 = trimestral, 365 = anual', verbose_name='Duración (días)')),
                ('max_classes_per_month', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para ilimitadas', null=True, verbose_name='Clases máximas por mes')),
                ('includes_trainer', models.BooleanField(default=False, verbose_name='Incluye entrenador personal')),
                ('can_freeze', models.BooleanField(default=True, verbose_name='Puede congelarse')),
                ('max_freeze_days', models.PositiveIntegerField(default=15, verbose_name='Días máximos de congelación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('frozen', 'Congelada'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('frozen_at', models.DateField(blank=True, null=True, verbose_name='Congelada desde')),
                ('frozen_days_used', models.PositiveIntegerField(default=0, verbose_name='Días de congelación usados')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member', verbose_name='Miembro')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='memberships.membership', verbose_name='Membresía')),
            ],
            options={
                'verbose_name': 'Congelación de Membresía',
                'verbose_name_plural': 'Congelaciones de Membresía',
                'ordering': ['-start_date'],
            },
        ),
    ]
