# Generated by Django 5.2.10 on 2026-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='freeze_days_per_year',
            field=models.IntegerField(default=14, verbose_name='Días de congelación por año'),
        ),
        migrations.AddField(
            model_name='membership',
            name='max_classes_per_month',
            field=models.IntegerField(blank=True, help_text='Dejar en blanco para ilimitado', null=True, verbose_name='Máximo de clases por mes'),
        ),
    ]
