# Generated by Django - Data Migration
"""
Migración de datos para crear perfiles Staff para todos los usuarios con rol 'trainer'
que no tengan un perfil Staff asociado.

Esta migración asegura que:
1. Todos los usuarios trainer tengan un perfil Staff
2. El perfil Staff tenga staff_type='trainer'
3. Sea reproducible y segura para ejecutar en producción
"""

from django.db import migrations
from django.utils import timezone


def create_staff_profiles_for_trainers(apps, schema_editor):
    """
    Crear perfiles Staff para todos los usuarios trainer que no tengan uno
    """
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    Staff = apps.get_model('staff', 'Staff')
    
    # Obtener el rol trainer
    try:
        trainer_role = Role.objects.get(name='trainer')
    except Role.DoesNotExist:
        print("⚠ Rol 'trainer' no existe, saltando migración")
        return
    
    # Encontrar todos los usuarios con rol trainer
    trainer_users = User.objects.filter(role=trainer_role)
    
    created_count = 0
    skipped_count = 0
    
    for user in trainer_users:
        # Verificar si ya tiene perfil Staff
        if Staff.objects.filter(user=user).exists():
            print(f"  ⊙ {user.email} ya tiene perfil Staff")
            skipped_count += 1
            continue
        
        # Crear perfil Staff
        Staff.objects.create(
            user=user,
            hire_date=timezone.now().date(),
            staff_type='trainer',
        )
        print(f"  ✓ Perfil Staff creado para: {user.email}")
        created_count += 1
    
    print(f"\n✓ Migración completada:")
    print(f"  - Perfiles creados: {created_count}")
    print(f"  - Usuarios ya tenían perfil: {skipped_count}")
    print(f"  - Total usuarios trainer: {trainer_users.count()}")


def reverse_migration(apps, schema_editor):
    """
    Revertir la migración (opcional - no hace nada por seguridad)
    """
    print("⚠ Reversión no implementada por seguridad de datos")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('staff', '__first__'),  # Asegurar que staff existe
    ]

    operations = [
        migrations.RunPython(
            create_staff_profiles_for_trainers,
            reverse_migration
        ),
    ]
