# Generated by Django 5.2.10 on 2026-01-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('trainer', 'Entrenador'), ('receptionist', 'Recepcionista'), ('admin', 'Administrativo'), ('maintenance', 'Mantenimiento')], default='trainer', max_length=20, verbose_name='Tipo de personal')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='Lista de especializaciones: ["Yoga", "CrossFit", "Pilates"]', verbose_name='Especializaciones')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certificaciones')),
                ('hire_date', models.DateField(verbose_name='Fecha de contratación')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por hora')),
                ('is_instructor', models.BooleanField(default=True, verbose_name='Es instructor de clases')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staff', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('staff', 'day_of_week', 'start_time')},
            },
        ),
    ]
