# Generated by Django 5.2.10 on 2026-01-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('weight_loss', 'Pérdida de peso'), ('weight_gain', 'Aumento de peso'), ('attendance', 'Asistencia'), ('class_completed', 'Clase completada'), ('milestone', 'Hito'), ('challenge', 'Reto'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Tipo de logro')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('achieved_date', models.DateField(verbose_name='Fecha del logro')),
                ('icon', models.CharField(default='trophy', max_length=50, verbose_name='Ícono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['-achieved_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Porcentaje de grasa corporal')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa muscular (kg)')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pecho (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cadera (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='members.member', verbose_name='Miembro')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Progreso',
                'verbose_name_plural': 'Registros de Progreso',
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
