# Generated by Django 5.2.7 on 2026-02-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('progress', '0001_initial'),
        ('workouts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (minutos)')),
                ('notes', models.TextField(blank=True, help_text='Cómo se sintió, dificultades, etc.', verbose_name='Notas del atleta')),
                ('trainer_feedback', models.TextField(blank=True, verbose_name='Feedback del entrenador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='members.member', verbose_name='Miembro')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutroutine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_sets', models.PositiveIntegerField(verbose_name='Series planeadas')),
                ('planned_reps', models.PositiveIntegerField(verbose_name='Repeticiones planeadas')),
                ('actual_sets', models.PositiveIntegerField(verbose_name='Series realizadas')),
                ('actual_reps', models.PositiveIntegerField(verbose_name='Repeticiones realizadas')),
                ('weight_used', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso usado (kg)')),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text='Qué tan difícil fue el ejercicio', null=True, verbose_name='Dificultad (1-10)')),
                ('completed', models.BooleanField(default=True, verbose_name='Completado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='Ejercicio')),
                ('routine_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.routineexercise', verbose_name='Ejercicio de rutina')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='progress.workoutsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Log de Ejercicio',
                'verbose_name_plural': 'Logs de Ejercicios',
                'ordering': ['id'],
            },
        ),
    ]
