# Generated by Django 5.2.10 on 2026-01-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Número de serie')),
                ('location', models.CharField(blank=True, help_text='Ej: Sala de cardio, Área de pesas', max_length=100, verbose_name='Ubicación')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de garantía')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('maintenance', 'En mantenimiento'), ('out_of_order', 'Fuera de servicio')], default='available', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='URL de imagen')),
                ('is_reservable', models.BooleanField(default=False, verbose_name='Puede reservarse')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmentcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Hora de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de fin')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='equipment.equipment', verbose_name='Equipo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Reserva de Equipo',
                'verbose_name_plural': 'Reservas de Equipos',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('emergency', 'Emergencia'), ('inspection', 'Inspección')], default='preventive', max_length=20, verbose_name='Tipo de mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha completada')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('performed_by', models.CharField(blank=True, max_length=100, verbose_name='Realizado por')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
