# Generated by Django 5.2.10 on 2026-01-29 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('FAILED_LOGIN', 'Intento de Login Fallido'), ('ACCESS', 'Acceso al Gimnasio'), ('FREEZE', 'Congelar'), ('UNFREEZE', 'Descongelar'), ('CANCEL', 'Cancelar'), ('EXPORT', 'Exportar'), ('VIEW', 'Visualizar')], db_index=True, max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(db_index=True, help_text='Nombre del modelo afectado (ej: Payment, Membership)', max_length=100, verbose_name='Modelo')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(blank=True, help_text='Representación en texto del objeto', max_length=255, verbose_name='Representación del Objeto')),
                ('changes', models.JSONField(blank=True, help_text='Diccionario con valores antes/después', null=True, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y sistema operativo', max_length=255, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('extra_data', models.JSONField(blank=True, help_text='Información contextual adicional', null=True, verbose_name='Datos Adicionales')),
                ('success', models.BooleanField(default=True, help_text='Si la acción se completó exitosamente', verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de Sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Login')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Logout')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('location', models.CharField(blank=True, help_text='Ciudad/País si está disponible', max_length=100, verbose_name='Ubicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='audit_users_user_id_cdca99_idx'), models.Index(fields=['is_active'], name='audit_users_is_acti_75d3be_idx')],
            },
        ),
    ]
