# Generated by Django 5.2.10 on 2026-01-09 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% Grasa corporal')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa muscular (kg)')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pecho (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cadera (cm)')),
                ('biceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bíceps (cm)')),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muslo (cm)')),
                ('resting_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='FC en reposo (bpm)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión sistólica')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión diastólica')),
                ('bench_press_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Press banca máx (kg)')),
                ('squat_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sentadilla máx (kg)')),
                ('deadlift_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso muerto máx (kg)')),
                ('pushups_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Flexiones (cantidad)')),
                ('situps_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Abdominales (cantidad)')),
                ('plank_duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plancha (segundos)')),
                ('vo2_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VO2 máx')),
                ('run_time_1km', models.DurationField(blank=True, null=True, verbose_name='Tiempo 1km')),
                ('sit_and_reach', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sit and reach (cm)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_performed', to='staff.staff', verbose_name='Evaluado por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_assessments', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Evaluación Física',
                'verbose_name_plural': 'Evaluaciones Físicas',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Pérdida de peso'), ('weight_gain', 'Aumento de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('strength', 'Fuerza'), ('flexibility', 'Flexibilidad'), ('health', 'Salud general'), ('custom', 'Personalizado')], default='health', max_length=20, verbose_name='Tipo de meta')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: peso objetivo, tiempo, repeticiones', max_digits=10, null=True, verbose_name='Valor objetivo')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor actual')),
                ('unit', models.CharField(blank=True, help_text='Ej: kg, min, rep', max_length=20, verbose_name='Unidad')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('achieved', 'Lograda'), ('abandoned', 'Abandonada')], default='active', max_length=20, verbose_name='Estado')),
                ('achieved_date', models.DateField(blank=True, null=True, verbose_name='Fecha lograda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías diarias')),
                ('protein_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Proteínas (g)')),
                ('carbs_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carbohidratos (g)')),
                ('fat_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grasas (g)')),
                ('meals_per_day', models.PositiveIntegerField(default=3, verbose_name='Comidas por día')),
                ('meal_details', models.JSONField(blank=True, default=dict, help_text='JSON con el detalle de cada comida', verbose_name='Detalle de comidas')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restricciones alimentarias')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_plans_created', to='staff.staff', verbose_name='Creado por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
                'ordering': ['-created_at'],
            },
        ),
    ]
