# Generated by Django 5.2.10 on 2026-01-14 20:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='cardio_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala 1-10', null=True, verbose_name='Nivel cardiovascular'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completada el'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('athlete', 'Atleta')], max_length=20, null=True, verbose_name='Nivel de fitness'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='flexibility_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala 1-10', null=True, verbose_name='Nivel de flexibilidad'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Condiciones médicas, lesiones, restricciones', verbose_name='Notas médicas'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='personal_goals',
            field=models.TextField(blank=True, help_text='Lo que el cliente quiere lograr', verbose_name='Objetivos personales'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 14, 20, 23, 8, 905081, tzinfo=datetime.timezone.utc), verbose_name='Fecha de solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Programada para'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='strength_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala 1-10', null=True, verbose_name='Nivel de fuerza'),
        ),
        migrations.AlterField(
            model_name='fitnessassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_performed', to='staff.staff', verbose_name='Evaluado por'),
        ),
    ]
