# Generated by Django 5.2.10 on 2026-01-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración por defecto (minutos)')),
                ('default_capacity', models.PositiveIntegerField(default=20, verbose_name='Capacidad por defecto')),
                ('color', models.CharField(default='#3B82F6', help_text='Color hexadecimal para el calendario', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Clase',
                'verbose_name_plural': 'Tipos de Clase',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad máxima')),
                ('location', models.CharField(blank=True, help_text='Ej: Sala 1, Área de pesas, Piscina', max_length=100, verbose_name='Ubicación')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.classtype', verbose_name='Tipo de clase')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='staff.staff', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la rutina')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de ejercicios')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20, verbose_name='Nivel de dificultad')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='staff.staff', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff', verbose_name='Asignada por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='members.member', verbose_name='Miembro')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.routine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Asignación de Rutina',
                'verbose_name_plural': 'Asignaciones de Rutinas',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('waitlist', 'Lista de espera'), ('cancelled', 'Cancelada'), ('attended', 'Asistió'), ('no_show', 'No asistió')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición en lista de espera')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asistencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='classes.gymclass', verbose_name='Clase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-reserved_at'],
                'unique_together': {('gym_class', 'member')},
            },
        ),
    ]
