# Generated by Django 5.2.10 on 2026-01-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('medical_notes', models.TextField(blank=True, help_text='Alergias, condiciones, etc.', verbose_name='Notas médicas')),
                ('subscription_status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('expired', 'Vencido'), ('frozen', 'Congelado')], default='inactive', max_length=20, verbose_name='Estado de suscripción')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_access', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['-created_at'],
            },
        ),
    ]
