# Generated by Django 5.2.10 on 2026-01-09 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('signed_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de firma')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Vencido'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado')),
                ('terms', models.TextField(blank=True, verbose_name='Términos y condiciones')),
                ('pdf_file', models.CharField(blank=True, max_length=255, verbose_name='Archivo PDF')),
                ('signed_by_member', models.BooleanField(default=False, verbose_name='Firmado por miembro')),
                ('signed_by_gym', models.BooleanField(default=False, verbose_name='Firmado por gimnasio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-signed_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Identificación'), ('medical', 'Certificado médico'), ('photo', 'Foto'), ('waiver', 'Exoneración'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de documento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file_path', models.CharField(max_length=255, verbose_name='Ruta del archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado el')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member', verbose_name='Miembro')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General'), ('class', 'Clase'), ('trainer', 'Entrenador'), ('facility', 'Instalaciones'), ('equipment', 'Equipamiento'), ('service', 'Servicio al cliente')], default='general', max_length=20, verbose_name='Tipo de feedback')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anónimo')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta del gimnasio')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='members.member', verbose_name='Miembro')),
                ('related_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='classes.gymclass', verbose_name='Clase relacionada')),
                ('related_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='staff.staff', verbose_name='Personal relacionado')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(max_length=100, verbose_name='Tipo de exoneración')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('signed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de firma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('signature_data', models.TextField(blank=True, help_text='Firma digital base64', verbose_name='Datos de firma')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='Aceptado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='members.member', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Exoneración',
                'verbose_name_plural': 'Exoneraciones',
                'ordering': ['-signed_date'],
            },
        ),
    ]
