# Generated by Django 6.0.1 on 2026-02-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20, verbose_name='Dificultad')),
                ('equipment_needed', models.CharField(blank=True, help_text='Ej: Mancuernas, barra, máquina', max_length=200, verbose_name='Equipo necesario')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', verbose_name='URL de video')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('instructions', models.TextField(help_text='Paso a paso de ejecución', verbose_name='Instrucciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_created', to='staff.staff', verbose_name='Creado por')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.musclegroup', verbose_name='Grupo muscular')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la rutina')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('goal', models.TextField(help_text='Lo que se busca lograr con esta rutina', verbose_name='Objetivo')),
                ('duration_weeks', models.PositiveIntegerField(help_text='Por cuántas semanas es esta rutina', verbose_name='Duración (semanas)')),
                ('is_active', models.BooleanField(default=True, help_text='Solo puede haber una rutina activa por miembro', verbose_name='Activa')),
                ('notified_at', models.DateTimeField(blank=True, help_text='Fecha en que se notificó al cliente', null=True, verbose_name='Notificado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_routines', to='members.member', verbose_name='Miembro')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines_created', to='staff.staff', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Rutina de Entrenamiento',
                'verbose_name_plural': 'Rutinas de Entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la semana')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de ejecución dentro del día', verbose_name='Orden')),
                ('sets', models.PositiveIntegerField(verbose_name='Series')),
                ('reps', models.PositiveIntegerField(help_text='Repeticiones por serie', verbose_name='Repeticiones')),
                ('rest_seconds', models.PositiveIntegerField(help_text='Segundos de descanso entre series', verbose_name='Descanso (seg)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso sugerido si aplica', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('notes', models.TextField(blank=True, help_text='Instrucciones específicas para este ejercicio', verbose_name='Notas')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='Ejercicio')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutroutine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio en Rutina',
                'verbose_name_plural': 'Ejercicios en Rutina',
                'ordering': ['day_of_week', 'order'],
                'unique_together': {('routine', 'exercise', 'day_of_week', 'order')},
            },
        ),
    ]
