# Generated by Django 6.0.1 on 2026-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_approved_at_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('membership', 'Pago de Membresía'), ('product', 'Compra de Producto'), ('service', 'Servicio Adicional'), ('other', 'Otro')], default='membership', help_text='Categoría del pago', max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
